german_name: "DIE&nbspRINGELROBBE"
german_splitted_name: "DIE&nbspRINGEL ROBBE"
russian_name: "КОЛЬЧАТАЯ&nbspНЕРПА"
russian_splitted_name: "КОЛЬЧАТАЯ НЕРПА"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      source: ""
      excerpt: ""
  -
    scope:
      path: ""
    values:
      image: /assets/site-image.png

permalink: pretty

url: "https://ringelrobbe.xyz"

title: Die Ringelrobbe - Кольчатая нерпа
tagline: Blog für Sprachpraxis
description: Die Übersetzungen aus dem Russichen und umgekehrt. Переводы с немецкого на русский и обратно.

logo: /assets/site-logo.png

author: Die Ringelrobbe

twitter:
  username: ringelr0bbe
  card: summary

webmaster_verifications:
  google: JUCToRj8k-mYn4pVdJTqTOmiu40oM06U9-yNrxqkU7E
  yandex: 0799069c2f9a48e4


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
